resources:
  # Upstream docker images
  - name: image-bb-gitversion-tool
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: 0.6.2

  - name: image-golang
    type: docker-image
    source:
      repository: golang
      tag: 1.15.6-buster

  # Git sources
  - name: source
    type: git
    source:
      uri: ((git_source))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

  # Github release
  - name: gh-release
    type: github-release
    source:
      owner: ci4rail
      repository: release_test
      access_token: ((github_access_token))
      release: false
      pre_release: true

jobs:
  - name: build-((name))
    public: true
    plan:
      - in_parallel:
          - get: image-bb-gitversion-tool
          - get: source
            trigger: true
          - get: image-golang
      - task: generate-version
        image: image-bb-gitversion-tool
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gitversion
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh &&
                jq empty gitversion/json/gitversion.json &&
                cat gitversion/json/gitversion.json
          params:
            GIT_PATH: source
            GEN_PATH: gitversion

      - task: build-kyt-cli
        image: image-golang
        config:
          platform: linux
          inputs:
            - name: source
            - name: gitversion
          outputs:
            - name: install
          run:
            path: /bin/bash
            args:
              - -ec
              - |
                ROOT=$(pwd)
                cd ${ROOT}/source/test
                make
                cp ../bin/* ${ROOT}/install

      - put: gh-release
        params:
          name: gitversion/plain/InformationalVersion
          tag: gitversion/plain/InformationalVersion
          globs:
            - install/*
