resources:
  # Git sources
  # testing
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((private_key))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))

jobs:
  - name: build
    plan:
      - get: source
        trigger: true

      - task: output
        config:
          platform: linux

          image_resource:
            type: registry-image
            source:
              repository: cfmanteiga/alpine-bash-curl-jq
              tag: latest
          inputs:
            - name: source
          run:
            path: /bin/bash
            args:
              - -c
              - |
                echo triggered pipeline
                cat source/.git/short_ref
